#!/bin/bash

if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Solapowa Temperatures'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_scale no'
	echo 'graph_category solapowa'
	echo 't1a.label T1'
	echo 't1a.draw LINE'
	echo 't3a.label T3'
	echo 't3a.draw LINE'
	echo 't4b.label T4'
	echo 't4b.draw LINE'
	exit 0
fi

# awk '{printf "uptime.value %.2f\n",$1/86400}' /proc/uptime
file="/var/tmp/solapowa.txt"

echo -n "t1a.value "
cat $file | grep "T1 temperature" | awk '{ print $3; }'

echo -n "t3a.value "
cat $file | grep "T3 temperature" | awk '{ print $3; }'

echo -n "t4b.value "
cat $file | grep "T4 temperature" | awk '{ print $5; }'

